### ISSUE TITLE
Dataset IDs shown in result of `czso_get_catalogue()` do not work in `czso_get_table()`

### ISSUE THREAD

**Issue by petrbouchal** [petrbouchal/czso#44]
# Current workaround

1. run `czso_get_catalogue()`
2. identify dataset you need
3. go to the URL listed in the `page` column
4. look at the `Kód` item at the top of the page - a code in the form of 123456-21
5. use the first six digits of this code as the `dataset_id` parameter to `czso_get_table()`

You can replace steps 1-3 with Google.

# Issue

This is caused by the new version of the local open data catalogue (LKOD) deployed by the data provider. The field `dct:identifier` in the National Data Catalogue (NKOD) used to contain the CZSO dataset code, but now contains the full URL of the metadata for the dataset in the LKOD.

# Solution

I am talking to the data provider to understand
- whether this is the intended end state
- whether they can also publish the CZSO dataset ID (Kód) in the NKOD/LKOD responses so the this package can have backward compatibility

Once I hear back, I will either rewrite the code to handle the new catalogue with a breaking change, or rewrite without a breaking change if the original IDs can be provided by the new catalogue, or provide a transitional fallback mechanism that will rely on the old LKOD, but the recommended way will be to use the new IDs as provided by both LKOD and NKOD.

**Comment by jlacko** [comment]
This is a most unfortunate behavior (on the part of the API). I noticed it today and was about to file a ticket - only to learn you are aware of the problem.

Thumbs up & fingers crossed for an acceptable resolution  (Staťák being staťák...)

**Comment by MartinCernyCZSO** [comment]
Staťák is trying to be helpful :-)
In addition to an old API (still in operation) and the new API (now registered in the National Catalogue of Open Data aka NKOD) the Czech Statistical Office has just published another API function to provide a more comprehensive list of datasets in CSV format using the old Dataset_ID - https://vdb.czso.cz/pll/eweb/lkod_ld.seznam 
Any adjustments to this API function are possible.

**Comment by jlacko** [comment]
@MartinCernyCZSO we appreciate Staťák being helpful, and I was harsh... My apologies. It just is that when you find a tool useful you come to rely on it - and then find any breaking change rather inconvenient. I was lucky to have the API fail on me only in a private project, not something public like teaching or what not...
 
The third API - https://vdb.czso.cz/pll/eweb/lkod_ld.seznam - seems very reasoneable.

@petrbouchal - do you need any help with implementing the new api call into `czso_get_table()` - it need not be a rocket science, and I would be happy to provide a pull request.

**Comment by MartinCernyCZSO** [comment]
API function https://vdb.czso.cz/pll/eweb/lkod_ld.seznam was adjusted:
- extra rows (due to multiple data formats) removed: CSV format preferred
- "temporal" field removed

The resulting list does not comprise 2 CZSO datatsets registered in NKOD:
- [Výsledky voleb do zastupitelstev obcí 2014](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00025593%2F240802)
- [Základní výsledky Sčítání lidu, domů a bytů 2011](https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00025593%2F240781)
They were registered in NKOD manually and are not handled by the API.

**Comment by petrbouchal** [comment]
Thanks both, especially @MartinCernyCZSO for the quick fix on the API part - indeed very helpful.

There is now a (probably temporary) fix in the package, in master via #45 and on its way to CRAN as version 0.3.5. (Thanks @jlacko for offering help - it was so simple that I just went ahead and made the change.)

We are still in conversation separately about what the final shape of the API will be, so further change to the package is likely, but I will try to minimise disruption faced by the package users.
