### ISSUE TITLE
Lexical error / invalid character when calling for codebook No. 1035 / DELCASI

### ISSUE THREAD

**Issue by jlacko** [petrbouchal/czso#53]
A call for the codebook 1035 / [DELCASI](https://apl2.czso.cz/iSMS/cisdet.jsp?kodcis=1035) errors out.
```r
czso::czso_get_codelist("cis1035")
# Error: lexical error: invalid character inside string.
#           du (alfanumerický kód) :  a)	1. znak - čas intervalu, nab
#                      (right here) ------^
```
At a glance it seems possible that the problem may be related to the formatting of an underlying JSON object (i.e. possibly a problem on the CZSO side), but I did not have the time to look into execution of the underlying code so this is just a guess.

**Comment by MartinCernyCZSO** [comment]
The „invalid character inside string“ is actually a tab character which is used in the documentation of the codelist 1035 – available at https://apl.czso.cz/iSMS/cisinfo.jsp?kodcis=1035

In general, the documentation of any CZSO dataset may contain any characters.

Martin Cerny
Czech Statistical Office (CZSO)


From: Jindra Lacko ***@***.***>
Sent: Sunday, March 31, 2024 10:50 PM
To: petrbouchal/czso ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [petrbouchal/czso] Lexical error / invalid character when calling for codebook No. 1035 / DELCASI (Issue #53)


A call for the codebook 1035 / DELCASI<https://apl2.czso.cz/iSMS/cisdet.jsp?kodcis=1035> errors out.

czso::czso_get_codelist("cis1035")

# Error: lexical error: invalid character inside string.

#           du (alfanumerický kód) :  a)      1. znak - čas intervalu, nab

#                      (right here) ------^

At a glance it seems possible that the problem may be related to the formatting of an underlying JSON object (i.e. possibly a problem on the CZSO side), but I did not have the time to look into execution of the underlying code so this is just a guess.

**Comment by petrbouchal** [comment]
Thanks for the report. Yes - it's the tab characters inside the JSON fields. I'll report to CZSO but may just as well add a sanitisation step.

**Comment by petrbouchal** [comment]
Note to self for further use

```r
library(czso)
debug(czso::czso_get_dataset_metadata)
czso::czso_get_dataset_metadata("1035")
```

**Comment by jlacko** [comment]
Thank you both for your kind comments; the issue is not a show stopper - in my use case easily sidestepped by downloading the codebook directly - so no (big) worries! 

I just wanted to file a ticket so it gets a chance of getting fixed in one of the future releases.

**Comment by petrbouchal** [comment]
Thank you @MartinCernyCZSO for the explanation. I had guessed this was happening because the metadata is transferred directly into the JSON.

However, because of the unescaped tab character inside a token, it is technically invalid JSON - see p. 2 at https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf:

> Insignificant whitespace is allowed before or after any token. Whitespace is any sequence of one or more of
the following code points: character tabulation (U+0009), line feed (U+000A), carriage return (U+000D), and
space (U+0020). Whitespace is not allowed within any token, except that space is allowed in strings.

I can handle this inside the package, but it might be worth fixing upstream at the point when the text is inserted into the JSON file served by the API.

**Comment by MartinCernyCZSO** [comment]
The documentations for CZSO open datasets are usually in a form of web pages and the contents are not provided in JSON format.
If you read the link to the documentation from CZSO API, e.g. https://vdb.czso.cz/pll/eweb/lkod_ld.datova_sada?id=cis1035, it will refer to a web page not to a JSON file. 
I am not sure which "JSON file served by the API" you are referring to.

**Comment by petrbouchal** [comment]
Sorry - not a file, just API result. It is in the "legacy" (I think) API: https://vdb.czso.cz/pll/eweb/package_show?id=cis1035.

**Comment by MartinCernyCZSO** [comment]
This API (https://vdb.czso.cz/pll/eweb/package_show?id=cis1035) is really outdated and not recommended to use.
The description for cis1035 used in this API has been fixed now but the same problem may occur for another dataset.

The correct API links for CZSO open datasets are:
1) https://vdb.czso.cz/pll/eweb/lkod_ld.katalog
2a) https://vdb.czso.cz/pll/eweb/lkod_ld.datova_sada?nazev=Ciselnik_CSU_Casovy_interval_kod_1035
2b) https://vdb.czso.cz/pll/eweb/lkod_ld.datova_sada?id=cis1035 (in case you prefer the old "id")

**Comment by petrbouchal** [comment]
Thanks - I will rewrite it eventually to use the newer API.
